export const APP_ROUTES = {
    home: "/",
    operations: "/operations",
    stores: "/stores",
    storeDetails: "/stores/studio",
    balance: "/balance",
    documents: "/documents",
    events: "/events",
    documentation: "/documentation",
    company: "/company",
    companyApplication: "/company/application",
    companyApplicationSignatory: "/company/application/signatory",
    companyApplicationPayoutAccounts: "/company/application/payout-accounts",
    companyApplicationReview: "/company/application/review",
    users: "/users",
    companyCreate: "/company/new",
    signIn: "/sign-in",
    signUp: "/sign-up",
    error: "/error",
} as const;
